# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: SSH@0
  inputs:
    sshEndpoint: 'one instance'
    runOptions: 'inline'
    inline: |
      #!/bin/bash
      echo 'start'
      # sudo su
      echo 'git clone'
      git clone https://github.com/yifa-n/skillbook.git -q
      echo ' mv file'
      sudo rm -rf /var/www/html/*
      sudo cp  -r skillbook/* /var/www/html/
      echo 'delete file'
      rm -rf skillbook
      echo 'finish'
    readyTimeout: '20000'
